apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ragt-sep18-1-gitops
  description: This is GitOps manifest for ragt-sep18-1   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ragt-sep18-1
    janus-idp.io/tekton: ragt-sep18-1 
    backstage.io/kubernetes-id: ragt-sep18-1 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ragt-sep18-1
