kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  ragt-sep18-1-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: ragt-sep18-1-dsp-job
    namespace: ragt-sep18-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ragt-sep18-1-imagestream-job-role
